from enum import Enum


class DDLStatementType(str, Enum):

    CREATE_TABLE = "CREATE_TABLE"

    ALTER_TABLE = "ALTER_TABLE"

    CREATE_INDEX = "CREATE_INDEX"

    CREATE_UNIQUE_INDEX = "CREATE_UNIQUE_INDEX"

    CREATE_FOREIGN_KEY = "CREATE_FOREIGN_KEY"

    COMMENT_TABLE = "COMMENT_TABLE"

    COMMENT_COLUMN = "COMMENT_COLUMN"

    DROP_TABLE = "DROP_TABLE"